/**
 * Created by Porter on 8/12/2017.
 */

var topics = [
    "Fire",
    "Water",
    "Crime",
    "Bacon",
    "Ugly",
    "Fast",
    "Slow",
    "Women",
    "Men",
    "Gay",
    "Hotels",
    "Rental Car",
    "Help",
    "Suicide",
    "Trump",
    "War",
    "Money",
    "Tax",
    "Futbol",
    "Football",
    "Soccer",
    "Hamburger",
    "McDonalds",
    "Immigration",
    "Subway",
    "Lice",
    "Zika",
    "Malaria",
    "Murder",
    "Guns",
    "Obesity",
    "Pokemon",
    "Pikachu",
    "Minecraft",
    "Roblox",
    "Runescape",
    "World of Warcraft",
    "PS4",
    "Xbox",
    "Mosquito",
    "Marvel",
    "Food",
    "Porn",
    "Islam",
    "Christianity",
    "Jesus",
    "Satan",
    "Religion",
    "Atheism",
    "Heavy Metal",
    "Metallica",
    "Taylor Swift",
    "Justin Bieber",
    "Iron Maiden",
    "Pop Music",
    "K-pop",
    "Hollywood",
    "Bollywood",
    "Whiskey",
    "Rum",
    "Beer",
    "Nightclub",
    "Disco",
    "Party",
    "Drugs",
    "Cocaine",
    "Meth",
    "Alcohol",
    "Heroine",
    "Marijuana",
    "Butts",
    "Boobs",
    "Harry Potter",
    "Legos",
    "Disney",
    "Mickey Mouse",
    "Tinkerbell",
    "NBA",
    "Hockey",
    "Basketball",
    "Golf",
    "Tennis",
    "Badminton",
    "Cricket",
    "Dragonball",
    "Anime",
    "Manga",
    "Crossfit",
    "Olympics",
    "FIFA",
    "World Cup",
    "Messi",
    "Ronaldo",
    "Ronaldinho",
    "Neymar",
    "Lebron James",
    "Michael Jordan",
    "Steph Curry",
    "James Harden",
    "Kim Kardashian",
    "Keeping Up With The Kardashians",
    "Ozzy Osbourne",
    "Simon Cowell",
    "50 Shades of Grey",
    "Video Games",
    "Reddit",
    "Netflix",
    "Netflix and Chill",
    "Sonic the Hedgehog",
    "Mario",
    "Nintendo",
    "Zelda",
    "Queen Elizabeth",
    "Devil",
    "Bible",
    "Koran",
    "Mosque",
    "Temple",
    "Jew",
    "Rasicm",
    "Police",
    "Hitman",
    "Prostitute",
    "Children",
    "Daycare",
    "Vacation",
    "Beach",
    "Cars",
    "Youtube",
    "Google",
    "Yahoo",
    "Amazon",
    "eBay",
    "iPhone",
    "Apple",
    "Android",
    "Hot",
    "Weather",
    "Hurricane",
    "Rain",
    "Snow",
    "Volcano",
    "Earthquake",
    "KFC",
    "Boner",
    "Horny",
    "Depressed",
    "Vegan",
    "Vegetarian",
    "Donuts",
    "Ice Cream"
];


var landmarks = [
    {name: "The Statue of Liberty", image:"/images/landmarks/statue_of_liberty.jpg",iso:'US'},
    {name: "The Eiffel Tower", image:"/images/landmarks/eiffel_tower.jpg",iso:'FR'},
    {name: "St. Basil's Cathedral", image:"/images/landmarks/eiffel_tower.jpg",iso:'RU'}
    // to be continued from http://designlike.com/100-most-famous-landmarks-around-the-world/
];

module.exports = {
    topics: topics,
    landmarks: landmarks,
    getTopics: function(array) {
        var items = [];
        for (var i = 0; i < 4; i++) {
            items[i] = module.exports[array][Math.floor(Math.random() * module.exports.topics.length)]
        }
        return items;
    }
};